name: gwas-ms-dashboard
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - streamlit=1.33.0
  - pandas=2.2.1
  - scikit-learn=1.4.1
  - xgboost=2.0.3
  - joblib=1.4.0
  - numpy=1.26.4
  - scipy=1.12.0
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - statsmodels=0.14.0
  - plotly=5.17.1
  - openpyxl=3.1.2
  - pyarrow=12.0.1